import {StyleSheet} from 'react-native';

export const styles = StyleSheet.create({
  page: {
    flex: 1,
    backgroundColor: '#F4F7FB',
    padding: 16,
  },
  loginPage: {
    flex: 1,
    backgroundColor: '#0060AF',
    paddingHorizontal: 20,
  },
  loginKeyboardWrap: {
    flex: 1,
  },
  loginContent: {
    flex: 1,
    justifyContent: 'flex-start',
    zIndex: 1,
    paddingTop: 28,
  },
  loginHeader: {
    marginTop: 8,
    marginBottom: 18,
    paddingHorizontal: 4,
  },
  loginAppTitle: {
    fontSize: 36,
    fontWeight: '800',
    color: '#FFFFFF',
    marginBottom: 10,
    letterSpacing: 0.2,
  },
  loginDescription: {
    fontSize: 16,
    lineHeight: 23,
    color: 'rgba(255,255,255,0.85)',
  },
  loginIntroText: {
    fontSize: 15,
    lineHeight: 22,
    color: 'rgba(255,255,255,0.87)',
    marginBottom: 8,
  },
  loginLogoWrap: {
    width: '100%',
    alignItems: 'center',
    marginBottom: 6,
  },
  loginLogo: {
    width: 136,
    height: 136,
    opacity: 0.95,
    alignSelf: 'center',
  },
  loginCard: {
    backgroundColor: '#1A5FAF',
    borderRadius: 18,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.28)',
    padding: 16,
    marginTop: 66,
  },
  loginInput: {
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.26)',
    borderRadius: 16,
    backgroundColor: 'rgba(255,255,255,0.18)',
    paddingHorizontal: 16,
    paddingVertical: 15,
    marginBottom: 14,
    fontSize: 16,
    color: '#F8FAFC',
  },
  loginPrimaryBtn: {
    backgroundColor: '#FFFFFF',
    paddingVertical: 16,
    borderRadius: 16,
    alignItems: 'center',
    marginTop: 8,
  },
  loginPrimaryBtnText: {
    color: '#0060AF',
    fontWeight: '700',
    fontSize: 15,
  },
  loginPrimaryBtnDisabled: {
    opacity: 0.65,
  },
  loginGoogleBtn: {
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    paddingVertical: 16,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#FFFFFF',
  },
  loginGoogleBtnDisabled: {
    opacity: 0.65,
  },
  loginGoogleBtnText: {
    color: '#1F2937',
    fontWeight: '800',
    fontSize: 15,
  },
  loginDividerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginVertical: 16,
  },
  loginDividerLine: {
    flex: 1,
    height: 1,
    backgroundColor: 'rgba(255,255,255,0.22)',
  },
  loginDividerText: {
    color: 'rgba(255,255,255,0.72)',
    fontSize: 12,
    fontWeight: '700',
    marginHorizontal: 10,
  },
  heroCard: {
    marginTop: 36,
    borderRadius: 24,
    backgroundColor: '#0B3D91',
    padding: 24,
  },
  badge: {
    color: '#FFE9A8',
    fontWeight: '700',
    marginBottom: 8,
  },
  heroTitle: {
    fontSize: 28,
    color: '#FFF',
    fontWeight: '800',
  },
  heroDesc: {
    marginTop: 8,
    color: '#D7E6FF',
    marginBottom: 20,
    lineHeight: 20,
  },
  title: {
    fontSize: 22,
    fontWeight: '800',
    marginBottom: 14,
    color: '#1F2937',
  },
  headerRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  logoutBtn: {
    borderWidth: 1,
    borderColor: '#CBD5E1',
    borderRadius: 10,
    backgroundColor: '#FFF',
    paddingHorizontal: 10,
    paddingVertical: 7,
  },
  logoutBtnText: {
    color: '#475569',
    fontWeight: '700',
    fontSize: 13,
  },
  subtitle: {
    fontSize: 15,
    color: '#475569',
    marginBottom: 12,
    lineHeight: 21,
  },
  input: {
    borderWidth: 1,
    borderColor: '#D1D5DB',
    borderRadius: 12,
    backgroundColor: '#FFF',
    paddingHorizontal: 12,
    paddingVertical: 11,
    marginBottom: 12,
    fontSize: 15,
  },
  searchRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: 12,
  },
  searchInput: {
    flex: 1,
    marginBottom: 0,
  },
  clearBtn: {
    borderWidth: 1,
    borderColor: '#CBD5E1',
    borderRadius: 10,
    backgroundColor: '#FFF',
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  clearBtnText: {
    color: '#475569',
    fontWeight: '700',
    fontSize: 13,
  },
  resultCountText: {
    color: '#334155',
    fontSize: 14,
    fontWeight: '600',
    marginBottom: 10,
  },
  rowWrap: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginBottom: 10,
  },
  categoryExpandedBox: {
    marginBottom: 10,
  },
  categoryExpandedList: {
    maxHeight: 170,
  },
  categoryExpandedContent: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    paddingBottom: 8,
  },
  categoryExpandedFooter: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    alignItems: 'center',
    gap: 8,
  },
  categoryCollapsedRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: 10,
  },
  categoryScroll: {
    flex: 1,
  },
  categoryScrollContent: {
    flexDirection: 'row',
    gap: 8,
    paddingRight: 2,
  },
  chip: {
    borderRadius: 999,
    borderWidth: 1,
    borderColor: '#CBD5E1',
    paddingHorizontal: 12,
    paddingVertical: 7,
    backgroundColor: '#FFF',
  },
  chipActive: {
    backgroundColor: '#0B3D91',
    borderColor: '#0B3D91',
  },
  chipText: {color: '#334155'},
  chipTextActive: {color: '#FFF'},
  categoryMoreBtn: {
    borderRadius: 999,
    borderWidth: 1,
    borderColor: '#0B3D91',
    backgroundColor: '#EAF1FF',
    paddingHorizontal: 12,
    paddingVertical: 7,
  },
  categoryMoreBtnText: {
    color: '#0B3D91',
    fontWeight: '700',
  },
  card: {
    backgroundColor: '#FFF',
    borderRadius: 14,
    padding: 14,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: '#E5E7EB',
  },
  cardDisabled: {
    backgroundColor: '#F8FAFC',
    borderColor: '#CBD5E1',
  },
  cardTitle: {
    fontSize: 17,
    fontWeight: '700',
    color: '#111827',
    marginBottom: 4,
  },
  statusRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 4,
  },
  statusText: {
    color: '#0B3D91',
    fontWeight: '700',
    fontSize: 13,
  },
  soldOutText: {
    color: '#B91C1C',
    fontWeight: '700',
    fontSize: 13,
  },
  cardMeta: {
    color: '#4B5563',
    marginBottom: 2,
    fontSize: 14,
    lineHeight: 20,
  },
  mutedText: {
    color: '#64748B',
    fontSize: 13,
    marginTop: 6,
  },
  primaryBtn: {
    backgroundColor: '#0B3D91',
    paddingVertical: 13,
    borderRadius: 12,
    alignItems: 'center',
    marginTop: 12,
  },
  primaryBtnDisabled: {
    backgroundColor: '#94A3B8',
  },
  primaryBtnText: {
    color: '#FFF',
    fontWeight: '700',
    fontSize: 15,
  },
  secondaryBtn: {
    borderWidth: 1,
    borderColor: '#0B3D91',
    backgroundColor: '#EAF1FF',
    paddingVertical: 13,
    borderRadius: 12,
    alignItems: 'center',
    marginVertical: 10,
  },
  secondaryBtnText: {
    color: '#0B3D91',
    fontWeight: '700',
    fontSize: 15,
  },
  dangerGhostBtn: {
    marginTop: 10,
    alignSelf: 'flex-start',
    borderWidth: 1,
    borderColor: '#FCA5A5',
    backgroundColor: '#FEF2F2',
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 7,
  },
  dangerGhostBtnText: {
    color: '#B91C1C',
    fontWeight: '700',
    fontSize: 13,
  },
  editGhostBtn: {
    marginTop: 10,
    alignSelf: 'flex-start',
    borderWidth: 1,
    borderColor: '#93C5FD',
    backgroundColor: '#EFF6FF',
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 7,
  },
  editGhostBtnText: {
    color: '#1D4ED8',
    fontWeight: '700',
    fontSize: 13,
  },
  inlineBtnRow: {
    flexDirection: 'row',
    gap: 8,
    alignItems: 'center',
  },
  inlineSaveBtn: {
    backgroundColor: '#0B3D91',
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  inlineSaveBtnText: {
    color: '#FFF',
    fontWeight: '700',
    fontSize: 13,
  },
  inlineCancelBtn: {
    borderWidth: 1,
    borderColor: '#CBD5E1',
    borderRadius: 10,
    backgroundColor: '#FFF',
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  inlineCancelBtnText: {
    color: '#475569',
    fontWeight: '700',
    fontSize: 13,
  },
  emptyText: {
    textAlign: 'center',
    marginTop: 24,
    color: '#6B7280',
    fontSize: 15,
    lineHeight: 22,
  },
});


